-- =====================================================================
-- 001_schema.sql — el esquema base, TAL CUAL lo creaste ya en tu
-- proyecto de Supabase. Este archivo se guarda en el repositorio solo
-- como referencia/documentación (para poder recrear la base de datos
-- desde cero si algún día hace falta) — NO hace falta volver a
-- ejecutarlo si ya tienes estas tablas creadas.
-- =====================================================================

-- Gastos puntuales (y los que se generan solos desde gastos fijos)
create table public.gastos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fecha date not null,
  categoria text not null,
  importe numeric(10,2) not null check (importe > 0),
  metodo_pago text,
  nota text,
  created_at timestamptz not null default now()
);

-- Ingresos puntuales
create table public.ingresos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fecha date not null,
  concepto text not null,
  importe numeric(10,2) not null check (importe > 0),
  created_at timestamptz not null default now()
);

-- Gastos fijos / recurrentes
create table public.gastos_fijos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  concepto text not null,
  categoria text not null,
  importe numeric(10,2) not null check (importe > 0),
  frecuencia text not null,
  metodo_pago text,
  proxima_fecha date not null,
  activo boolean not null default true,
  nota text,
  created_at timestamptz not null default now()
);

-- Ingreso fijo de cada mes concreto (tu "nómina" variable mes a mes)
create table public.ingresos_fijos_mensuales (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mes date not null,
  importe numeric(10,2) not null check (importe >= 0),
  unique (user_id, mes)
);

-- Ajustes de cada persona: dinero inicial y nómina base sugerida
create table public.perfil (
  user_id uuid primary key references auth.users(id) on delete cascade,
  dinero_inicial numeric(10,2),
  nomina_base numeric(10,2) not null default 0
);

-- Seguridad: cada persona solo puede ver y tocar SUS propias filas, nunca las de otra
alter table public.gastos enable row level security;
alter table public.ingresos enable row level security;
alter table public.gastos_fijos enable row level security;
alter table public.ingresos_fijos_mensuales enable row level security;
alter table public.perfil enable row level security;

create policy "gastos: solo el dueño" on public.gastos
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ingresos: solo el dueño" on public.ingresos
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "gastos_fijos: solo el dueño" on public.gastos_fijos
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ingresos_fijos_mensuales: solo el dueño" on public.ingresos_fijos_mensuales
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "perfil: solo el dueño" on public.perfil
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
