-- =====================================================================
-- 004_modificaciones_v2.sql
--
-- EJECUTA ESTE ARCHIVO ENTERO UNA VEZ en el SQL Editor de tu proyecto
-- de Supabase (con 001, 002 y 003 ya ejecutados). Añade lo pedido en la
-- segunda ronda de mejoras:
--
--   1. Gastos fijos "de importe variable" (luz, agua...): en vez de
--      cargarse solos con un importe inventado, se quedan pendientes
--      de que tú confirmes el importe real ese mes.
--   2. Ingresos fijos con la misma estructura que Gastos fijos (varias
--      entradas recurrentes, cada una con su frecuencia y su fecha, en
--      vez de un único importe por mes) — sustituye al desplegable de
--      mes que había antes.
--   3. Necesario / prescindible: cada categoría tiene una clasificación
--      por defecto, y cada gasto (o gasto fijo) puede saltársela si
--      hace falta.
--   4. Enlace entre cada gasto/ingreso generado automáticamente y el
--      gasto/ingreso fijo del que viene, para poder comparar "lo mismo
--      con lo mismo" en la nueva pestaña de Anomalías.
--
-- No borra ni toca ningún dato que ya tengas guardado. Las tablas
-- "ingresos_fijos_mensuales" y la columna "nomina_base" de "perfil" se
-- quedan como están (ya no se usan para nada nuevo, pero no hace falta
-- borrarlas — no molestan).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) Columnas nuevas en "gastos_fijos" y "gastos"
-- ---------------------------------------------------------------------
alter table public.gastos_fijos
  add column if not exists variable boolean not null default false,
  add column if not exists tipo_gasto text check (tipo_gasto in ('necesario', 'prescindible'));

alter table public.gastos
  add column if not exists gasto_fijo_id bigint references public.gastos_fijos(id) on delete set null,
  add column if not exists tipo_gasto text check (tipo_gasto in ('necesario', 'prescindible'));

comment on column public.gastos_fijos.variable is
  'Si es true, este gasto fijo NO se añade solo a "gastos" cuando llega su fecha: se queda pendiente de que confirmes el importe real (ver procesar_gastos_fijos()).';
comment on column public.gastos.gasto_fijo_id is
  'Si el gasto viene de un gasto fijo (automático o confirmado a mano), aquí se guarda de cuál — para poder comparar su historial en la pestaña Anomalías.';
comment on column public.gastos.tipo_gasto is
  'Anula, solo para este gasto, la clasificación necesario/prescindible por defecto de su categoría. NULL = usa la de la categoría.';
comment on column public.gastos_fijos.tipo_gasto is
  'Igual que gastos.tipo_gasto, pero para la plantilla del gasto fijo: se copia a cada ocurrencia que se genere.';

-- ---------------------------------------------------------------------
-- 2) Tabla nueva "ingresos_fijos" (mismo patrón que "gastos_fijos", sin
--    categoría) + columna de enlace en "ingresos"
-- ---------------------------------------------------------------------
create table if not exists public.ingresos_fijos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  concepto text not null,
  importe numeric(10,2) not null check (importe > 0),
  frecuencia text not null,
  metodo_pago text,
  proxima_fecha date not null,
  activo boolean not null default true,
  variable boolean not null default false,
  nota text,
  created_at timestamptz not null default now()
);

alter table public.ingresos_fijos enable row level security;

drop policy if exists "ingresos_fijos: solo el dueño" on public.ingresos_fijos;
create policy "ingresos_fijos: solo el dueño" on public.ingresos_fijos
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- RLS solo decide QUÉ FILAS puede tocar cada persona; sin este permiso a
-- nivel de tabla, "authenticated" no puede ni intentar el SELECT/INSERT/
-- UPDATE/DELETE (las tablas creadas a mano desde el Table Editor de
-- Supabase ya lo traen solas; una tabla creada por SQL como esta, no).
grant select, insert, update, delete on table public.ingresos_fijos to authenticated;

alter table public.ingresos
  add column if not exists ingreso_fijo_id bigint references public.ingresos_fijos(id) on delete set null,
  add column if not exists metodo_pago text;

comment on column public.ingresos.ingreso_fijo_id is
  'Si el ingreso viene de un ingreso fijo (automático o confirmado a mano), aquí se guarda de cuál. NULL = ingreso puntual, como hasta ahora.';

-- ---------------------------------------------------------------------
-- 3) Vista "resumen_mensual": ahora que los ingresos fijos generan sus
--    propias filas en "ingresos" (en vez de un único importe por mes
--    en "ingresos_fijos_mensuales"), se calcula "ingresos fijos" y
--    "ingresos puntuales" del mes distinguiendo por "ingreso_fijo_id".
-- ---------------------------------------------------------------------
create or replace view public.resumen_mensual
with (security_invoker = true) as
with meses as (
  select user_id, date_trunc('month', fecha)::date as mes from public.ingresos
  union
  select user_id, date_trunc('month', fecha)::date as mes from public.gastos
),
gastos_mes as (
  select user_id, date_trunc('month', fecha)::date as mes, sum(importe) as total
  from public.gastos
  group by 1, 2
),
ingresos_fijos_mes as (
  select user_id, date_trunc('month', fecha)::date as mes, sum(importe) as total
  from public.ingresos
  where ingreso_fijo_id is not null
  group by 1, 2
),
ingresos_puntuales_mes as (
  select user_id, date_trunc('month', fecha)::date as mes, sum(importe) as total
  from public.ingresos
  where ingreso_fijo_id is null
  group by 1, 2
)
select
  m.user_id,
  m.mes,
  coalesce(fi.total, 0) as ingresos_fijos,
  coalesce(pu.total, 0) as ingresos_puntuales,
  coalesce(fi.total, 0) + coalesce(pu.total, 0) as ingresos_totales,
  coalesce(g.total, 0) as gastos,
  (coalesce(fi.total, 0) + coalesce(pu.total, 0)) - coalesce(g.total, 0) as ahorro
from meses m
left join gastos_mes g on g.user_id = m.user_id and g.mes = m.mes
left join ingresos_fijos_mes fi on fi.user_id = m.user_id and fi.mes = m.mes
left join ingresos_puntuales_mes pu on pu.user_id = m.user_id and pu.mes = m.mes;

grant select on public.resumen_mensual to authenticated;

-- ---------------------------------------------------------------------
-- 4) Automatización: procesar_gastos_fijos() ahora SALTA los gastos
--    fijos marcados como "variable" (se quedan con su proxima_fecha
--    sin avanzar, a la espera de que confirmes el importe desde la
--    app), enlaza cada gasto generado con su gasto fijo de origen, y
--    llama a la nueva procesar_ingresos_fijos() en vez de
--    procesar_nomina() (que ya no hace falta, aunque se deja definida
--    por si acaso).
-- ---------------------------------------------------------------------
create or replace function public.procesar_gastos_fijos()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  gf record;
  fecha_cursor date;
  meses_paso int;
  tope int;
  nota_final text;
begin
  for gf in select * from public.gastos_fijos where activo and not variable loop
    fecha_cursor := gf.proxima_fecha;
    meses_paso := case gf.frecuencia
      when 'Mensual' then 1
      when 'Trimestral' then 3
      when 'Semestral' then 6
      when 'Anual' then 12
      else 1
    end;
    tope := 0;

    while fecha_cursor <= current_date and tope < 60 loop
      nota_final := 'Fijo: ' || gf.concepto ||
        case when coalesce(gf.nota, '') <> '' then ' — ' || gf.nota else '' end;

      insert into public.gastos (user_id, fecha, categoria, importe, metodo_pago, nota, gasto_fijo_id, tipo_gasto)
      values (gf.user_id, fecha_cursor, gf.categoria, gf.importe, gf.metodo_pago, nota_final, gf.id, gf.tipo_gasto);

      fecha_cursor := (fecha_cursor + (meses_paso || ' months')::interval)::date;
      tope := tope + 1;
    end loop;

    if tope > 0 then
      update public.gastos_fijos set proxima_fecha = fecha_cursor where id = gf.id;
    end if;
  end loop;

  perform public.procesar_ingresos_fijos();
end;
$$;

-- ---------------------------------------------------------------------
-- 5) Nueva procesar_ingresos_fijos(): igual que procesar_gastos_fijos()
--    pero para "ingresos_fijos" → "ingresos". También salta los
--    marcados como "variable" (p. ej. una nómina que cambia cada mes).
-- ---------------------------------------------------------------------
create or replace function public.procesar_ingresos_fijos()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  inf record;
  fecha_cursor date;
  meses_paso int;
  tope int;
  concepto_final text;
begin
  for inf in select * from public.ingresos_fijos where activo and not variable loop
    fecha_cursor := inf.proxima_fecha;
    meses_paso := case inf.frecuencia
      when 'Mensual' then 1
      when 'Trimestral' then 3
      when 'Semestral' then 6
      when 'Anual' then 12
      else 1
    end;
    tope := 0;

    while fecha_cursor <= current_date and tope < 60 loop
      concepto_final := 'Fijo: ' || inf.concepto ||
        case when coalesce(inf.nota, '') <> '' then ' — ' || inf.nota else '' end;

      insert into public.ingresos (user_id, fecha, concepto, importe, metodo_pago, ingreso_fijo_id)
      values (inf.user_id, fecha_cursor, concepto_final, inf.importe, inf.metodo_pago, inf.id);

      fecha_cursor := (fecha_cursor + (meses_paso || ' months')::interval)::date;
      tope := tope + 1;
    end loop;

    if tope > 0 then
      update public.ingresos_fijos set proxima_fecha = fecha_cursor where id = inf.id;
    end if;
  end loop;
end;
$$;

-- Nota: procesar_nomina() (de 002_views_and_automations.sql) se queda
-- definida pero deja de llamarse desde aquí — "ingresos_fijos_mensuales"
-- y "nomina_base" ya no alimentan ningún cálculo nuevo. No hace falta
-- borrar nada: simplemente no se usan más.

-- El cron ya programado en 002 ("procesar-gastos-fijos-diario") sigue
-- llamando a procesar_gastos_fijos() cada día a las 6:00 UTC — no hace
-- falta reprogramarlo, ya que esa misma función ahora también procesa
-- los ingresos fijos al final.

-- Ejecuta la automatización una vez ahora mismo, para dejar todo al día:
select public.procesar_gastos_fijos();
