-- =====================================================================
-- 005_presupuestos.sql
-- (ejecuta una vez en el SQL Editor, con 001, 002, 003 y 004 ya
-- ejecutados)
--
-- Añade el presupuesto mensual: un límite total opcional (columna
-- nueva en "perfil") y límites opcionales por categoría (tabla nueva
-- "presupuestos_categoria"). No hace falta nada en el cron ni en las
-- funciones de gastos/ingresos fijos: los avisos de presupuesto (al
-- 80% y al pasarte) se calculan enteramente en el navegador,
-- comparando lo que llevas gastado con estos límites — no se guarda
-- ningún histórico mes a mes, el mismo límite se aplica siempre hasta
-- que lo cambies.
-- =====================================================================

alter table public.perfil
  add column if not exists presupuesto_mensual numeric(10,2) check (presupuesto_mensual >= 0);

comment on column public.perfil.presupuesto_mensual is
  'Límite de gasto total al que te avisas a ti mismo cada mes (80% y al pasarte). NULL = sin presupuesto configurado.';

create table if not exists public.presupuestos_categoria (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  categoria text not null,
  importe numeric(10,2) not null check (importe > 0),
  created_at timestamptz not null default now(),
  unique (user_id, categoria)
);

comment on table public.presupuestos_categoria is
  'Límites de gasto mensual opcionales, uno por categoría como mucho. Las categorías sin fila aquí no tienen límite.';

alter table public.presupuestos_categoria enable row level security;

drop policy if exists "presupuestos_categoria: solo el dueño" on public.presupuestos_categoria;
create policy "presupuestos_categoria: solo el dueño" on public.presupuestos_categoria
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- RLS solo decide QUÉ FILAS puede tocar cada persona; sin este permiso a
-- nivel de tabla, "authenticated" no puede ni intentar el SELECT/INSERT/
-- UPDATE/DELETE (las tablas creadas a mano desde el Table Editor de
-- Supabase ya lo traen solas; una tabla creada por SQL como esta, no).
grant select, insert, update, delete on table public.presupuestos_categoria to authenticated;
